import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { test } from 'node:test'

const root = new URL('../../', import.meta.url)
const read = (path: string) => readFileSync(new URL(path, root), 'utf8')

test('wearable queue is signed-worker scoped and read only', () => {
  const persistence = read('lib/persistence/wearablePicking.ts')
  assert.match(persistence, /lower\(pick\.assigned_to\) = \$2/)
  assert.match(persistence, /pick\.status = 'ready'/)
  assert.match(persistence, /orders\.status = 'released'/)
  assert.match(persistence, /plan\.status = 'released'/)
  assert.match(persistence, /wave\.status = 'released'/)
  assert.match(persistence, /operations_product_channel_states channel/)
  assert.match(persistence, /channel\.provider_barcode/)
  assert.match(persistence, /channel\.provider_sku = line\.channel_sku/)
  assert.match(persistence, /crm_product_image_assets asset/)
  assert.match(persistence, /asset\.is_primary = true/)
  assert.match(persistence, /publicCrmProductImageUrl/)
  assert.doesNotMatch(persistence, /line\.barcode_snapshot/)
  assert.doesNotMatch(persistence, /\b(?:INSERT|UPDATE|DELETE)\b/)
})

test('wearable route keeps existing ClawPilot authorization boundary', () => {
  const route = read('app/api/operations/picks/route.ts')
  assert.match(route, /requireRequestUser\(req\)/)
  assert.match(route, /capabilities\.canView/)
  assert.match(route, /capabilities\.canExecute/)
  assert.doesNotMatch(route, /!capabilities\.canManage/)
  assert.match(route, /Cache-Control': 'private, no-store'/)
  assert.match(route, /import \{ appPublicUrl \} from '@\/lib\/publicUrl'/)
  assert.match(route, /publicOrigin: appPublicUrl\(\)/)
  assert.doesNotMatch(route, /publicOrigin: req\.nextUrl\.origin/)
})

test('Phase 1 confirmation reuses the audited Operations command', () => {
  const route = read('app/api/operations/route.ts')
  const persistence = read('lib/persistence/operations.ts')
  assert.match(route, /action === 'confirm-picks'/)
  assert.match(route, /idempotencyKeyValue\(req\)/)
  assert.match(persistence, /confirmOperationsOrderPicksFromPostgres/)
  assert.match(persistence, /OPERATIONS_ORDER_VERSION_CONFLICT/)
  assert.match(persistence, /operations\.pick\.completed/)
  assert.match(persistence, /operations\.order\.picks_confirmed/)
})

test('Meta universal-link metadata and callback remain public without exposing app data', () => {
  const proxy = read('proxy.ts')
  const association = read('lib/appleAppLinks.ts')
  const callback = read('app/ios/route.ts')
  assert.match(proxy, /pathname === '\/\.well-known\/apple-app-site-association'/)
  assert.match(proxy, /pathname === '\/apple-app-site-association'/)
  assert.match(proxy, /pathname === '\/ios'/)
  assert.match(proxy, /if \(isPublicAppleAppLink\(pathname\)\) return NextResponse\.next\(\)/)
  assert.match(association, /CN2T77JHQQ\.com\.eigenracing\.ios\.picking'/)
  assert.match(association, /CN2T77JHQQ\.com\.eigenracing\.ios\.picking\.dev'/)
  assert.match(association, /'\/': '\/ios\*'/)
  assert.doesNotMatch(callback, /requireRequestUser|resolveRequestSession|operations|pipeline/)
})

test('Meta DAT callback uses the app URL scheme and camera access requires registration', () => {
  const app = read('../clients/apple/Apps/iPhone/ClawPilotPickingPhoneApp.swift')
  const dashboard = read('../clients/apple/Apps/iPhone/PickingDashboardView.swift')
  const development = read('../clients/apple/Config/Development.xcconfig')
  const production = read('../clients/apple/Config/Production.xcconfig')
  assert.match(development, /CLAWPILOT_META_URL_SCHEME = clawpilot-meta-dev/)
  assert.match(development, /CLAWPILOT_META_APP_LINK_SCHEME = clawpilot-meta-dev:\/\$\(\)\//)
  assert.match(production, /CLAWPILOT_META_URL_SCHEME = clawpilot-meta/)
  assert.match(production, /CLAWPILOT_META_APP_LINK_SCHEME = clawpilot-meta:\/\$\(\)\//)
  assert.match(app, /if ClawPilotSystemActionLink\.requestsScan\(url\)/)
  assert.match(app, /await model\.handlePendingSystemScan\(\)/)
  assert.match(app, /await model\.handleMetaURL\(url\)/)
  assert.match(app, /guard MetaWearablesAppBridge\.isRegistered else/)
  assert.match(dashboard, /else if model\.canRequestMetaCamera/)
  assert.match(dashboard, /Button\("Allow camera access"\)/)
  assert.match(app, /await loadQueue\(readAloud: false\)/)
})

test('iPhone picking UI supports a dismissible one-time-code flow and branded icon', () => {
  const project = read('../clients/apple/project.yml')
  const dashboard = read('../clients/apple/Apps/iPhone/PickingDashboardView.swift')
  assert.match(project, /ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon/)
  assert.match(project, /UILaunchScreen: \{\}/)
  assert.match(dashboard, /Image\("ClawPilotMark"\)/)
  assert.match(dashboard, /\.textContentType\(\.oneTimeCode\)/)
  assert.match(dashboard, /ToolbarItemGroup\(placement: \.keyboard\)/)
  assert.match(dashboard, /Button\("Done"\) \{ authenticationField = nil \}/)
  assert.match(dashboard, /\.scrollDismissesKeyboard\(\.interactively\)/)
})

test('Watch companion presents safe pick context and routes commands through iPhone', () => {
  const project = read('../clients/apple/project.yml')
  const watch = read('../clients/apple/Apps/Watch/ClawPilotPickingWatchApp.swift')
  const bridge = read('../clients/apple/Apps/iPhone/PhoneWatchBridge.swift')
  const app = read('../clients/apple/Apps/iPhone/ClawPilotPickingPhoneApp.swift')
  assert.match(project, /ClawPilotPickingWatch:[\s\S]*ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon/)
  assert.match(watch, /AsyncImage\(url: url/)
  assert.match(watch, /model\.send\(\.requestMetaScan\)/)
  assert.match(watch, /model\.readInstruction\(\)/)
  assert.match(watch, /AVSpeechSynthesizer/)
  assert.match(watch, /Playing instruction on Apple Watch/)
  assert.match(watch, /model\.send\(\.confirmPick\)/)
  assert.match(watch, /model\.send\(\.refreshQueue\)/)
  assert.match(bridge, /decode\(WatchPickCommand\.self/)
  assert.match(bridge, /handledCommandIDs/)
  assert.match(app, /private func handleWatchCommand/)
  assert.match(app, /readInstructionOnPhone: metaConnectedDeviceCount == 1/)
  assert.doesNotMatch(watch, /PickingAPIClient|ConfirmPicksCommand/)
})

test('picker audio routing and Meta scan feedback stay explicit and bounded', () => {
  const voice = read('../clients/apple/Apps/iPhone/VoiceConfirmationController.swift')
  const app = read('../clients/apple/Apps/iPhone/ClawPilotPickingPhoneApp.swift')
  const dashboard = read('../clients/apple/Apps/iPhone/PickingDashboardView.swift')
  const meta = read('../clients/apple/Apps/iPhone/MetaWearablesBarcodeSource.swift')
  const intent = read('../clients/apple/Apps/iPhone/ClawPilotScanIntent.swift')
  const settings = read('../clients/apple/Apps/iPhone/Settings.bundle/Root.plist')
  assert.match(voice, /setCategory\(\s*\.playback,/)
  assert.match(voice, /\.allowBluetoothA2DP/)
  assert.match(voice, /overrideOutputAudioPort\(\.speaker\)/)
  assert.match(settings, /clawpilot_audio_playback/)
  assert.match(settings, /clawpilot_instruction_language/)
  assert.match(settings, /Always iPhone speaker/)
  assert.doesNotMatch(settings, /clawpilot_speech_voice/)
  assert.match(voice, /let preferredNames = \["Ava", "Zoe", "Samantha", "Nicky", "Allison"\]/)
  assert.match(voice, /\$0\.quality != \.default && \$0\.identifier != systemVoice\?\.identifier/)
  assert.match(voice, /\.first \?\? systemVoice/)
  assert.match(app, /Task\.sleep\(for: \.seconds\(15\)\)/)
  assert.match(app, /Hey Siri, scan with ClawPilot/)
  assert.match(app, /await source\.stop\(\)[\s\S]*await accept\(value, source: \.metaGlasses\)/)
  assert.match(app, /await voice\.speakAndWait\(\s*"Item matched\. Say confirm pick to submit\.",\s*spanish: "Producto correcto\. Di confirmar pedido para enviarlo\."\s*\)/)
  assert.match(app, /await listenForConfirmation\(automatic: true\)/)
  assert.match(app, /timeout: automatic \? \.seconds\(8\) : nil/)
  assert.match(app, /voice\.speak\("Picks confirmed\.", spanish: "Pedido confirmado\."\)[\s\S]*await loadQueue\(readAloud: false\)/)
  assert.match(voice, /import SupertonicTTS/)
  assert.match(voice, /aufklarer\/Supertonic-3-CoreML-FP16/)
  assert.match(voice, /voicePackStorageRoot[\s\S]*"ClawPilotPicking"[\s\S]*"models"[\s\S]*"aufklarer"[\s\S]*"Supertonic-3-CoreML-FP16"/)
  assert.match(voice, /voicePackStorageRoot:[\s\S]*\.applicationSupportDirectory/)
  assert.match(voice, /purgeableVoicePackDirectory/)
  assert.match(voice, /moveItem\(\s*at: purgeableVoicePackDirectory,\s*to: voicePackDirectory\s*\)/)
  assert.match(voice, /values\.isExcludedFromBackup = true/)
  assert.match(voice, /voice: language == \.spanish \? "F2" : "F1"/)
  assert.match(voice, /language: language\.languageCode/)
  assert.match(voice, /SupertonicOptions\(totalStep: 8, speed: 1\.05, seed: 42\)/)
  assert.match(voice, /written: "ClawPilot",\s*spoken: "Claw Pilot"/)
  assert.match(voice, /clawpilot_pronunciation_corrections/)
  assert.match(voice, /options: \[\.caseInsensitive\]/)
  assert.match(dashboard, /Pronunciation corrections/)
  assert.match(dashboard, /Save and preview/)
  assert.match(dashboard, /model\.removePronunciationCorrection/)
  assert.match(voice, /computeUnits: \.cpuAndGPU/)
  assert.match(voice, /sampleRate: 44_100/)
  assert.match(voice, /runOfflineVoiceSelfTest/)
  assert.match(voice, /nonisolated private static func requestSpeechAuthorization/)
  assert.match(voice, /let speechStatus = await Self\.requestSpeechAuthorization\(\)/)
  assert.match(voice, /pcm\.count > 44_100, finite, peak > 0\.01/)
  assert.match(app, /CLAWPILOT_VOICE_SELF_TEST/)
  assert.match(app, /CLAWPILOT_SPEECH_AUTH_SELF_TEST/)
  assert.match(app, /CLAWPILOT_LISTENING_SELF_TEST/)
  assert.match(voice, /let recognitionHandler: @Sendable/)
  assert.match(voice, /VectorEstimator\.mlpackage\/Data\/com\.apple\.CoreML\/weights\/weight\.bin": 255_276_032/)
  assert.match(voice, /voice_styles\/F2\.json": 292_423/)
  assert.match(voice, /Apple speech remains the fallback/)
  assert.match(voice, /Enhanced voice storage could not be prepared/)
  assert.match(meta, /resolution: \.high/)
  assert.match(meta, /photoDataPublisher\.listen[\s\S]*videoFramePublisher\.listen[\s\S]*camera\.stream\.start\(\)/)
  assert.match(meta, /photo-received:bytes=/)
  assert.match(meta, /video-received:/)
  assert.match(meta, /\.ean8, \.ean13, \.upce/)
  assert.match(meta, /\.code128, \.code39, \.code93/)
  assert.match(meta, /\.gs1DataBar, \.gs1DataBarExpanded, \.gs1DataBarLimited/)
  assert.doesNotMatch(voice, /import KokoroTTS/)
  assert.doesNotMatch(app, /voice\.speak\("Glasses camera started\./)
  assert.match(dashboard, /Open ClawPilot App Settings/)
  assert.match(dashboard, /MPVolumeView/)
  assert.match(dashboard, /Choose audio output/)
  assert.match(dashboard, /Preview instruction voice/)
  assert.match(meta, /withCheckedThrowingContinuation/)
  assert.match(meta, /startContinuation\?\.resume\(\)/)
  assert.match(meta, /photoDataPublisher/)
  assert.match(meta, /capturePhoto\(format: \.jpeg\)/)
  assert.match(meta, /for _ in 0\.\.<6/)
  assert.match(meta, /VNImageRequestHandler\(\s*data: photo\.data/)
  assert.match(intent, /StartClawPilotGlassesScanIntent/)
  assert.match(intent, /Scan with \\\(.applicationName\)/)
  assert.match(intent, /OpenURLIntent\(ClawPilotSystemActionLink\.scanURL\(\)\)/)
  assert.match(intent, /clawpilot_action/)
  assert.match(intent, /clawpilot_last_scan_stage/)
  assert.match(intent, /clawpilot_scan_history/)
  assert.match(app, /ClawPilotScanDiagnostic\.record\("camera-live"\)/)
  assert.match(app, /ClawPilotScanDiagnostic\.record\("timeout:no-barcode"\)/)
  assert.match(app, /for attempt in 1\.\.\.3/)
  assert.match(meta, /error == \.datAppOnTheGlassesUpdateRequired/)
  assert.match(meta, /failStart\(MetaScanError\.glassesAppUpdateRequired\)/)
  assert.match(app, /if error as\? MetaScanError == \.glassesAppUpdateRequired \{ break \}/)
  assert.match(dashboard, /Button\("Update camera software in Meta AI"\)/)
  assert.match(dashboard, /Do not reset ClawPilot or re-pair the glasses/)
  assert.match(app, /guard !isHandlingPendingSystemScan else/)
  assert.match(app, /guard !isMetaScanning else/)
  assert.match(app, /MetaWearablesAppBridge\.startUnregistration\(\)/)
  assert.match(dashboard, /Button\("Reset and open Meta AI", role: \.destructive\)/)
  assert.match(dashboard, /It does not unpair your glasses/)
  assert.match(meta, /session-error:/)
  assert.match(meta, /stream-error:/)
})

test('mobile manager assignment reuses audited Operations concurrency controls', () => {
  const route = read('app/api/operations/route.ts')
  const persistence = read('lib/persistence/operations.ts')
  const pickers = read('app/api/operations/pickers/route.ts')
  assert.match(route, /action === 'assign-picks'/)
  assert.match(route, /idempotencyKeyValue\(req\)/)
  assert.match(route, /expectedRowVersion/)
  assert.match(persistence, /assignOperationsOrderPicksFromPostgres/)
  assert.match(persistence, /commandType: 'assign_operations_order_picks'/)
  assert.match(persistence, /order\.status !== 'released'/)
  assert.match(persistence, /pick\.status = 'ready'/)
  assert.match(persistence, /SET assigned_to = \$3/)
  assert.match(persistence, /eventType: 'operations\.pick\.assigned'/)
  assert.match(pickers, /operationsCapabilities\(actor\)/)
  assert.match(pickers, /permissions\.executeWarehouse/)
})

test('picker setup and UPH use durable Operations evidence', () => {
  const session = read('app/api/auth/session/route.ts')
  const queue = read('app/api/operations/picks/route.ts')
  const performance = read('app/api/operations/picker-performance/route.ts')
  const persistence = read('lib/persistence/wearablePicking.ts')
  const migration = read('../db/migrations/0256_operations_picker_performance.sql')
  const people = read('components/settings/UserAccessDialog.tsx')
  assert.match(session, /operations\.canView && operations\.canExecute/)
  assert.match(queue, /!capabilities\.canView \|\| !capabilities\.canExecute/)
  assert.match(performance, /readPickerPerformanceFromPostgres/)
  assert.match(performance, /managerScope \? null : actor\.email/)
  assert.match(persistence, /pick\.assigned_at/)
  assert.match(persistence, /pick\.picked_at/)
  assert.match(persistence, /EXTRACT\(epoch FROM completed_at - assigned_at\)/)
  assert.match(migration, /ADD COLUMN IF NOT EXISTS assigned_at timestamptz/)
  assert.match(people, /label: 'Picker access'/)
  assert.match(people, /next\.viewOperations = true/)
})

test('mobile app gates workflows behind the shared ClawPilot session', () => {
  const session = read('app/api/auth/session/route.ts')
  const app = read('../clients/apple/Apps/iPhone/ClawPilotPickingPhoneApp.swift')
  const shell = read('../clients/apple/Apps/iPhone/ClawPilotAppShellView.swift')
  assert.match(session, /mobileCapabilities:/)
  assert.match(session, /canUsePicker:/)
  assert.match(session, /canUseManager:/)
  assert.match(app, /api\.fetchSessionProfile\(\)/)
  assert.match(shell, /Sign in before choosing your workflow/)
  assert.match(shell, /case \.picker/)
  assert.match(shell, /case \.manager/)
  assert.match(shell, /Wave and assign order/)
})

test('mobile organization changes reuse the session workspace boundary and clear scoped picks', () => {
  const session = read('app/api/auth/session/route.ts')
  const workspace = read('app/api/auth/workspace/route.ts')
  const app = read('../clients/apple/Apps/iPhone/ClawPilotPickingPhoneApp.swift')
  const adapters = read('../clients/apple/Sources/ClawPilotPickingApple/AppleAdapters.swift')
  const pickingSession = read('../clients/apple/Sources/ClawPilotPickingCore/PickingSession.swift')
  const shell = read('../clients/apple/Apps/iPhone/ClawPilotAppShellView.swift')
  assert.match(session, /activeWorkspace:/)
  assert.match(session, /availableWorkspaces:/)
  assert.match(workspace, /switchBrowserSessionWorkspace/)
  assert.match(workspace, /clearWorkspaceSelectionCookies\(response\)/)
  assert.match(adapters, /api\/auth\/workspace/)
  assert.match(app, /guard canSwitchWorkspace else/)
  assert.match(app, /try await picking\.clearQueue\(\)/)
  assert.match(pickingSession, /public func clearQueue\(\) async throws/)
  assert.match(shell, /WorkspaceSwitcherCard\(model: model\)/)
  assert.match(shell, /WorkspaceSwitcherCard\(model: model, compact: true\)/)
})
