export const ONE_OFF_LIVE_POSTAGE_CONFIRMATION =
  'AUTHORIZE THIS LIVE POSTAGE PURCHASE'

export const ONE_OFF_PACK_CONFIRMATION =
  'I CONFIRM THESE EXACT ITEMS ARE PHYSICALLY IN THESE PACKAGES'

export const ONE_OFF_MAX_SYNCHRONOUS_PACKAGES = 40
